### ISSUE TITLE
update with modal BsHelper

### ISSUE THREAD

**Issue by lucasmc20** [WebAndCow/CakePHP-BsHelpers#28]
I'm doing a crud with BsForm with modal, but editing is not picking up, they click edit opens the modal without values and if you fill the data it updates. I would like to show the values in the modal.
you have any examples of crud with $ this-> BS-> modal

**Comment by Damiaou** [comment]
Hi, maybe this is what you are looking for : http://webandcow.github.io/CakePHP-BsHelpers/bshelper.html#components
If you look for the button 'form modal'.
You can get the full doc here but here comes an exemple : 

This code : 
$this->BsForm->create('Model', array('action' => 'myAction')).
$this->BsForm->input('field', array('value' => 'Whatever you want')).
$this->BsForm->end();
Create a form.

And this one : 
echo
$this->Bs->modal('My awesome modal 2', $form, array('form' => true), array('open' => array('name' => 'Form modal', 'class' => 'btn-danger'), 'confirm' => array('name' => 'Send', 'link' => array('controller' => 'myController', 'action' => 'myAction'))));
Put the previous form in a modal where users can fill the fields.
Hope it helps.
